#ifndef ITEM_PARAM_H
#define ITEM_PARAM_H

enum
{
    ITEM_DATA_PRICE,
    ITEM_DATA_USE_EFFECT,
    ITEM_DATA_USE_PARAM,
    ITEM_DATA_IS_IMPORT_ITEM,
    ITEM_DATA_CONV_BUTTON,
    ITEM_DATA_POCKET_FIELD,

    ITEM_DATA_IS_EVOSTONE = 0x1D,
};

#endif